import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import { FavoritesProvider } from "@/context/FavoritesContext";
import { CartProvider } from "@/context/CartContext";
import { ToastProvider } from "@/components/Toast";
import Navbar from "@/components/Navbar";
import { adminDb } from "@/lib/firebase/admin";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const { userId } = await auth();
  let showMyAccountLink = false;
  if (userId) {
    try {
      const snap = await adminDb.collection("customers").doc(userId).get();
      showMyAccountLink = snap.exists;
    } catch {
      showMyAccountLink = false;
    }
  }

  return (
    <ClerkProvider
      telemetry={false}
      authConfig={{ passwordEnabled: false }}
    >
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <ToastProvider>
            <CartProvider>
              <FavoritesProvider>
                <Navbar showMyAccountLink={showMyAccountLink} />
                {children}
              </FavoritesProvider>
            </CartProvider>
          </ToastProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
